# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

receivers:
  otlp:
    protocols:
      http:

processors:

exporters:
  debug:
    verbosity: detailed
  file:
    path: /var/log/otel.log

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug,file]
