#!/bin/bash
# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

export EBPF_NET_SRC="${EBPF_NET_SRC:-$(git rev-parse --show-toplevel)}"
# shellcheck source=/dev/null
source "${EBPF_NET_SRC}/dev/script/benv_error_lib.sh"
# shellcheck source=/dev/null
source "${EBPF_NET_SRC}/dev/script/benv_lib.sh"

docker exec "$(get_benv_container_name)" "${@}"

