// Code generated by "stringer -type=LogLevel"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Error-0]
	_ = x[Warn-1]
	_ = x[Info-2]
	_ = x[Debug-3]
	_ = x[Trace-4]
}

const _LogLevel_name = "ErrorWarnInfoDebugTrace"

var _LogLevel_index = [...]uint8{0, 5, 9, 13, 18, 23}

func (i LogLevel) String() string {
	if i < 0 || i >= LogLevel(len(_LogLevel_index)-1) {
		return "LogLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogLevel_name[_LogLevel_index[i]:_LogLevel_index[i+1]]
}
