set(OPENSSL_USE_STATIC_LIBS TRUE)
find_package(OpenSSL REQUIRED)
if (BUILD_WITH_OTLP)
  if (NOT OPENSSL_VERSION STREQUAL "1.1.1n")
	  message(FATAL_ERROR "OpenSSL must be a specific version (1.1.1n). Build container should already have that set up. Note that benv-final:v8 doesn't currently support building with OTLP - need to use a custom local benv build.")
  endif()
else()
  if (NOT OPENSSL_VERSION STREQUAL "1.1.1b")
	  message(FATAL_ERROR "OpenSSL must be a specific version (1.1.1b). Build container should already have that set up")
  endif()
endif()
