
name: snyk scans

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/snyk-scans.yml'

permissions:
  contents: read

jobs:
  snyk-scan:
    permissions:
      security-events: write # required for uploading SARIF
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Set up Snyk
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
      - name: Run Snyk to check for vulnerabilities
        run: |
          snyk test --unmanaged \ 
            --all-projects \
            --severity-threshold=high \
            --exclude=docs,cmake,ext \
            --detection-depth=5
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: false
        
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@b8d3b6e8af63cde30bdc382c0bc28114f4346c88 # v2
        with:
          sarif_file: snyk.sarif